// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYloSaoejnhLwFI6IFbXy-jXeLbjm3Bv8',
    appId: '1:47340804613:web:ccb33ce3c2da46cd6b1a6c',
    messagingSenderId: '47340804613',
    projectId: 'chat-f0afb',
    authDomain: 'chat-f0afb.firebaseapp.com',
    storageBucket: 'chat-f0afb.appspot.com',
    measurementId: 'G-PWMZ43ZMGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUSk_CACDbSaX0-VuHHzTe-NGBXqLW04',
    appId: '1:47340804613:android:894ccea6196916a56b1a6c',
    messagingSenderId: '47340804613',
    projectId: 'chat-f0afb',
    storageBucket: 'chat-f0afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCItv3SfjsbBFYTnRB9erSevzNZCT7YqKg',
    appId: '1:47340804613:ios:5873d612995b324e6b1a6c',
    messagingSenderId: '47340804613',
    projectId: 'chat-f0afb',
    storageBucket: 'chat-f0afb.appspot.com',
    androidClientId: '47340804613-39gvq1f2iitcm25a9abe5utio4nkgcaf.apps.googleusercontent.com',
    iosClientId: '47340804613-1mti3oqpcahc4u0rmprlqqdsdqcuh539.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCItv3SfjsbBFYTnRB9erSevzNZCT7YqKg',
    appId: '1:47340804613:ios:5873d612995b324e6b1a6c',
    messagingSenderId: '47340804613',
    projectId: 'chat-f0afb',
    storageBucket: 'chat-f0afb.appspot.com',
    androidClientId: '47340804613-39gvq1f2iitcm25a9abe5utio4nkgcaf.apps.googleusercontent.com',
    iosClientId: '47340804613-1mti3oqpcahc4u0rmprlqqdsdqcuh539.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
